version: '3.9'

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lk22642
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    env_file: 
      - .env
    ports: 
      - 4000:4000
      - 9229:9229 #DEBUG
    volumes:
      - .:/usr/app
      - /usr/app/node_modules   
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local